// Dropdown options derived from the model's trained one-hot columns
const CATEGORIES = {
  "State": [
    "Assam",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Tripura",
    "Unknown"
  ],
  "District": [
    "Anjaw",
    "Bishnupur",
    "Bongaigaon",
    "CHAMPHAI",
    "CHHITUIPUI",
    "Cachar",
    "Champhai",
    "Chandel",
    "Changlang",
    "Chumoukedima",
    "Churachandpur",
    "Dhalai",
    "Dibang Valley",
    "Dima Hasao",
    "Dima Hasao (N.C. Hills)",
    "Dimapur",
    "East Garo hills",
    "East Jaintia Hills",
    "East Kameng",
    "East Khasi Hills",
    "East Siang",
    "Eastern-West Khasi Hill",
    "Goalpara",
    "Gomati",
    "Hailakandi",
    "Hnahthial",
    "Imphal East",
    "Jaintia Hills",
    "Jiribam",
    "Jorhat",
    "Kamjong",
    "Kamle",
    "Kamrup",
    "Kamrup (Metro)",
    "Kamrup (Rural)",
    "Kangpokpi",
    "Karbi Anglong",
    "Karimganj",
    "Khawzawl",
    "Kiphire",
    "Kohima",
    "Kolasib",
    "Kra Daadi",
    "Kurung Kumey",
    "Lawngtlai",
    "Lepa rada",
    "Lohit",
    "Longding",
    "Longleng",
    "Lower Dibang Valley",
    "Lower Siang",
    "Lower Subansiri",
    "Lower dibang valley",
    "Lunglei",
    "MAMIT",
    "Mamit",
    "Moirang",
    "Mokokchung",
    "Mon",
    "Morigaon",
    "Nagaon",
    "Noklak",
    "Noney",
    "North Tripura",
    "Pakke Kessang",
    "Papum Pare",
    "Peren",
    "Phek",
    "Pherzawl",
    "Ri-Bhoi",
    "Saiha",
    "Saitual",
    "Senapati",
    "Serchhip",
    "Shi-Yomi",
    "Siaha",
    "Siang",
    "Sonitpur",
    "South Garo Hills",
    "South Garo hills",
    "South Tripura",
    "South West Garo Hills",
    "South West Khasi Hills",
    "TAMENGLONG",
    "Tamenglong",
    "Tawang",
    "Tengnoupal",
    "Thoubal",
    "Tirap",
    "Tseminyu",
    "Tuensang",
    "Udalguri",
    "Ukhrul",
    "Unknown",
    "Upper Siang",
    "Upper Subansiri",
    "West Garo Hills",
    "West Imphal",
    "West Jaintia Hills",
    "West Jaintia hills",
    "West Kameng",
    "West Karbi Anglong",
    "West Khasi Hills",
    "West Siang",
    "West Tripura",
    "Wokha",
    "Zunheboto"
  ],
  "Rainfall Pattern": [
    "Extremely wet; exceptionally high monsoon rainfall, especially southern Khasi-Jaintia uplands",
    "High; concentrated in SW monsoon, with substantial pre-monsoon rainfall",
    "Monsoon-dominated with a distinct wet season; rainfall varies with elevation",
    "Monsoon-dominated; comparatively lower rainfall in the Imphal valley than surrounding hills",
    "Monsoon-dominated; substantial pre-monsoon and post-monsoon contribution",
    "Strong monsoon rainfall with pronounced wet season; hilly terrain causes local variation",
    "Unknown",
    "Very wet; strong monsoon influence; rainfall varies greatly with altitude and relief"
  ],
  "Soil Distribution": [
    "Acidic hill soils; Inceptisols, Ultisols and Entisols; alluvial soils in valleys",
    "Alluvial in Brahmaputra/Surma valleys; red/yellow and older alluvial soils in hill/southern areas",
    "Red and yellow soils, with alluvial soils in valleys and lowlands; strongly acidic overall",
    "Red and yellow, moderately deep acidic soils; strongly leached hill soils",
    "Red and yellow, strongly acidic hill soils; highly weathered upland soils",
    "Red loamy and acidic hill soils; mainly Inceptisols/Ultisols in uplands",
    "Red/yellow and acidic hill soils; valley alluvium",
    "Unknown"
  ],
  "Vegetation": [
    "Subtropical broadleaf forests, pine forests, bamboo and grasslands",
    "Subtropical/temperate hill forests, bamboo and grasslands; valley agriculture",
    "Tropical evergreen/semi-evergreen and moist deciduous forests; bamboo and cane-rich vegetation",
    "Tropical evergreen/semi-evergreen and moist deciduous forests; grasslands and bamboo/tea landscapes",
    "Tropical evergreen/semi-evergreen forests, bamboo-rich vegetation and secondary vegetation",
    "Unknown",
    "Very dense subtropical, temperate and alpine forests; conifer/broadleaf zones with altitude"
  ]
};
